### ISSUE TITLE
Editor parameter isn't respected

### ISSUE THREAD

**Issue by hugosenari** [jiro4989/markx#1]
Hi,
Sorry to bother you (again).
I'm not sure if it's my system problem (NixOs is a really strange distro) or if `-e nvim`, `-e=nvim`, `--editor nvim` or `--editor=nvim` is overridden by $EDITOR (nano)

**Comment by jiro4989** [comment]
`markx` overrides `--editor` options by `EDITOR` environment variables. This is specifications of `markx`.

Please try this command (bash) if you want to remove `EDITOR` environment variables.

```bash
unset EDITOR
```

or override `EDITOR`.

```bash
export EDITOR=nvim
markx -e 'echo {}' 1 2 3 4
```

**Comment by jiro4989** [comment]
Ah..., I will change `--editor` and `EDITOR` priority.

**Comment by jiro4989** [comment]
I updated markx. Try this.

```bash
nimble install -Y markx
markx -e nano -c 'echo {}' 1 2 3
markx -e nvim -c 'echo {}' 1 2 3
```
